### ISSUE TITLE
include security context constraint as yaml

### ISSUE THREAD

**Issue by enrico2828** [lgchiaretto/openshift4-backup-automation#10]
Instead of using oc command to add sa to scc we can include also a yaml like this, which makes the git resource work out of the box without manual action:

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-backup-privileged
  namespace: ocp-backup-etcd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: openshift-backup
  namespace: ocp-backup-etcd
```
